services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-aiprimary  
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - /opt/datn-be/postgres-aiprimary:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - network-aiprimary
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M

  mongo:
    image: mongo:7-jammy
    container_name: mongodb-aiprimary
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    expose:
      - "27017"
    volumes:
      - /opt/datn-be/mongo-aiprimary:/data/db
    restart: unless-stopped
    networks:
      - network-aiprimary
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak-aiprimary
    command:
      - start
      - --import-realm
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

      # HTTP/HTTPS Configuration for production behind reverse proxy
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_URL=https://auth.huy-devops.site
      - KC_HOSTNAME_ADMIN_URL=https://auth.huy-devops.site
      - KC_HOSTNAME_STRICT=true
      - KC_HOSTNAME_STRICT_HTTPS=true
      - KC_PROXY=edge
      - KC_PROXY_HEADERS=xforwarded

      # Health check
      - KC_HEALTH_ENABLED=true

      # Database configuration
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres-aiprimary:5432/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_DB_SCHEMA=public

      # Logging
      - KC_LOG_LEVEL=info
    ports:
      - "8082:8080"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - network-aiprimary
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "1"
          memory: 256M

volumes:
  postgres-data:
  mongo-data:

networks:
  network-aiprimary:
    name: network-aiprimary
    driver: bridge
    external: true
