services:
  datn-be:
    # build: .
    image: ghcr.io/tien4112004/datn-be:latest
    container_name: backend-aiprimary
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
    environment:
      - POSTGRES_DB_URL=jdbc:postgresql://postgres-aiprimary:5432/${POSTGRES_DB}
      - POSTGRES_DB_USERNAME=${POSTGRES_USER}
      - POSTGRES_DB_PASSWORD=${POSTGRES_PASSWORD}

      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_REDIRECT_URI=${KEYCLOAK_REDIRECT_URI}
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - KEYCLOAK_CLIENT_UUID=${KEYCLOAK_CLIENT_UUID}
      - FE_URL=${FE_URL}
      - GOOGLE_CALLBACK_URI=${GOOGLE_CALLBACK_URI}

      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_PUBLIC_URL=${S3_PUBLIC_URL}
      - PHOENIX_API_URL=${PHOENIX_API_URL}
      - PHOENIX_API_KEY=${PHOENIX_API_KEY}
      - PHOENIX_PROJECT_ID=${PHOENIX_PROJECT_ID}

      - AI_API_BASE_URL=${AI_API_BASE_URL}
      - AI_API_OUTLINE_ENDPOINT=${AI_API_OUTLINE_ENDPOINT}
      - AI_API_OUTLINE_BATCH_ENDPOINT=${AI_API_OUTLINE_BATCH_ENDPOINT}
      - AI_API_PRESENTATION_ENDPOINT=${AI_API_PRESENTATION_ENDPOINT}
      - AI_API_PRESENTATION_BATCH_ENDPOINT=${AI_API_PRESENTATION_BATCH_ENDPOINT}
      - AI_API_IMAGE_ENDPOINT=${AI_API_IMAGE_ENDPOINT}
      - FIREBASE_CONFIG_PATH=file:/app/firebase-service-account.json
      - INITIAL_COIN_VALUE=${INITIAL_COIN_VALUE:-1000}

      - SPRING_PROFILES_ACTIVE=docker

      - SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT=60000

      - SSL_KEY_STORE_PASSWORD=${SSL_KEY_STORE_PASSWORD}

      - PAYOS_CLIENT_ID=${PAYOS_CLIENT_ID}
      - PAYOS_API_KEY=${PAYOS_API_KEY}
      - PAYOS_CHECKSUM_KEY=${PAYOS_CHECKSUM_KEY}

      - SEPAY_MERCHANTID=${SEPAY_MERCHANTID}
      - SEPAY_SECRET_KEY=${SEPAY_SECRET_KEY}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /actuator/health HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'",
        ]
      interval: 30s
      timeout: 10s
      start_period: 90s
      retries: 5
    ports:
      - "8081:8080"
    networks:
      - network-aiprimary
    volumes:
      - /opt/datn-be/ai-primary-backend-selfsigned.crt:/app/ssl/backend.crt:ro
      - /opt/datn-be/ai-primary-backend-selfsigned.key:/app/ssl/backend.key:ro
      - /opt/datn-be/ai-primary-backend.p12:/app/ssl/backend.p12:ro
      - /opt/datn-be/firebase-service-account.json:/app/firebase-service-account.json:ro

networks:
  network-aiprimary:
    name: network-aiprimary
    external: true
