services:
  datn-be:
    # build: .
    image: ghcr.io/tien4112004/datn-be:latest
    container_name: backend-aiprimary
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - POSTGRES_DB_URL=jdbc:postgresql://postgres-aiprimary:5432/${POSTGRES_DB}
      - POSTGRES_DB_USERNAME=${POSTGRES_USER}
      - POSTGRES_DB_PASSWORD=${POSTGRES_PASSWORD}

      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_REDIRECT_URI=${KEYCLOAK_REDIRECT_URI}
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - FE_URL=${FE_URL}
      - GOOGLE_CALLBACK_URI=${GOOGLE_CALLBACK_URI}
      
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL_DEV=${R2_PUBLIC_URL_DEV}
      - CLOUD_FLARE_API_TOKEN=${CLOUD_FLARE_API_TOKEN}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}

      - AI_API_BASE_URL
      - AI_API_OUTLINE_ENDPOINT
      - AI_API_OUTLINE_BATCH_ENDPOINT
      - AI_API_PRESENTATION_ENDPOINT
      - AI_API_PRESENTATION_BATCH_ENDPOINT
      - AI_API_IMAGE_ENDPOINT

      - SPRING_PROFILES_ACTIVE=docker

      - SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT=60000
      
      - SSL_KEY_STORE_PASSWORD=${SSL_KEY_STORE_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /actuator/health HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'",
        ]
      interval: 30s
      timeout: 10s
      start_period: 90s
      retries: 5
    ports:
      - "8081:8080"
    networks:
      - network-aiprimary
    volumes:
      - /opt/datn-be/ai-primary-backend-selfsigned.crt:/app/ssl/backend.crt:ro
      - /opt/datn-be/ai-primary-backend-selfsigned.key:/app/ssl/backend.key:ro
      - /opt/datn-be/ai-primary-backend.p12:/app/ssl/backend.p12:ro

networks:
  network-aiprimary:
    name: network-aiprimary
    external: true
